### ISSUE TITLE
Feature Request: Avoid Overwriting

### ISSUE THREAD

**Issue by kueblc** [seanh/gedit-smart-autosave#1]
Nice plugin, thanks for your hard work!

I'm looking for a way to autosave without overwriting the original file, until I manually save of course. Something like a cross between autosave and tilde backup.

Use case where I am using Gedit as a scratch pad and don't necessarily want to commit those changes, but also don't want to risk losing the work in case of an unexpected shutdown.

Is it possible to specify a different path for the autosaved file?

**Comment by seanh** [comment]
Hi, that's not possible with `gedit-smart-autosave`, sorry.

[gnome-text-editor](https://gitlab.gnome.org/GNOME/gnome-text-editor) (which recently replaced gedit as gnome's default text editor) works in just the way that I think you want by default: it silently autosaves everything to `~/.local/share/org.gnome.TextEditor/drafts/` so if there's a crash you won't lose anything, but you still have to manually press save to write the changes to the actual file.
